name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: sudo apt install doxygen pandoc && make
      - name: deploy
        run: |
        git config --global user.email "you@example.com"
        git config --global user.name "git"
        git add . && git commit -m "pages"
        git push -f origin master:gh-pages
